---
layout: doc
---

# 前端异步编程规范

::: tip 知识点

- 简版 Promise
- Promise/A+ 规范解读
- async/await 介绍
- generator 介绍

:::

::: details 目标

- 初级：
  - 掌握 Promise、async/await、generator 的定义及用法
  - 掌握前端异步编程，在项目中灵活应用
- 中级：
  - 手动实现 Promise 和 async/await
  - 掌握多种异步编程，了解异步编程的底层原理
  - 会封装项目中的异步框架，兼容多种场景
- 高级：
  - 深入了解异步编程的底层原理，在多场景中能够使用异步编程的思想，解决问题

:::

::: details 资料

- 官网MDN：https://developer.mozilla.org/en-US/docs/Web/JavaScript
- 画图工具🔧：https://www.processon.com/
- 在线画板：https://app.diagrams.net/
- 豆包旗下的智能编程助手Trae AI: https://www.marscode.com/extension

:::

## 1. 简版 Promise

### 1.1 Resolve 和 Reject
``` js
let p1 = new Promise((resolve, reject) => {
  resolve('成功')
  reject('失败')
})
console.log('p1', p1)

let p2 = new Promise((resolve, reject) => {
  reject('失败')
  resolve('成功')
})
console.log('p2', p2)

let p3 = new Promise((resolve, reject) => {
  throw new Error('失败')
})
console.log('p3', p3)
```
!['Promise'](/img/javascript/07.png)

这里说明了 `Promise` 的四个特点：
- 执行了 `resolve`，`Promise` 状态会变成 `fulfilled`
- 执行了 `reject`，`Promise` 状态会变成 `rejected`
- `Promise` 状态不可逆，第一次成功就永久为 `fulfilled`，第一次失败就永久为 `rejected`
- `Promise` 中有 `throw` 的话，就相当于执行了 `reject`

#### 1.1.1 实现 Resolve 和 Reject

1. `Promise` 的初始状态是 `pending`
2. 需要对 `resolve` 和 `reject` 绑定 `this`：确保 `resolve` 和 `reject` 内部的 `this` 指向 当前的`MyPromise` 实例，防止随着函数执行环境的改变而被改变
``` js
class MyPromise {
  // 构造方法
  constructor(executor) {
    // 初始化值
    this.initValue()
    // 初始化 this 指向
    this.initBind()
    // 执行传进来的函数
    executor(this.resolve, this.reject)
  }

  initValue(){
    // 初始化值
    this.PromiseResult = null // 存储最终结果
    this.PromiseState = 'pending' // 存储状态
  }

  initBind() {
    // 初始化 this 指向
    this.resolve = this.resolve.bind(this)
    this.reject = this.reject.bind(this)
  }

  resolve(value) {
    // 如果执行 resolve，状态就会变成 fulfilled
    this.PromiseState = 'fulfilled'
    // 最终结果为传入的值
    this.PromiseResult = value
  }

  reject(reason) {
    // 如果执行 reject，状态就会变成 rejected
    this.PromiseState = 'rejected'
    // 最终结果为传入的reason
    this.PromiseResult = reason
  }
}
```
测试如下：
``` js
const test1 = new MyPromise((resolve, reject) => {
  resolve('成功')
})
console.log('test1', test1)

const test2 = new MyPromise((resolve, reject) => {
  reject('失败')
})
console.log('test2', test2)
```
!['Promise'](/img/javascript/08.png)

#### 1.1.2 状态不可变
``` js
const test = new MyPromise((resolve, reject) => {
  resolve('成功')
  reject('失败')
})
console.log('test', test)
```
!['Promise'](/img/javascript/09.png)

正确的结果状态应该是 `fulfilled`，但是这里的状态又变成了 `rejected`。

`Promise` 有三种状态：
- `pending`: 等待中，是初始状态
- `fulfilled`: 成功状态
- `rejected`: 失败状态

一旦状态从 `pending` 变成 `fulfilled` 或 `rejected`，状态就不可以改变了。
!['Promise'](/img/javascript/10.png)

这步只需要：
``` js
class MyPromise {
  // 构造方法
  constructor(executor) {
    // 初始化值
    this.initValue()
    // 初始化 this 指向
    this.initBind()
    // 执行传进来的函数
    executor(this.resolve, this.reject)
  }

  initValue(){
    // 初始化值
    this.PromiseResult = null // 存储最终结果
    this.PromiseState = 'pending' // 存储状态
  }

  initBind() {
    // 初始化 this 指向
    this.resolve = this.resolve.bind(this)
    this.reject = this.reject.bind(this)
  }

  resolve(value) {
    // state 状态不可变
    if (this.PromiseState !== 'pending') return
    // 如果执行 resolve，状态就会变成 fulfilled
    this.PromiseState = 'fulfilled'
    // 最终结果为传入的值
    this.PromiseResult = value
  }

  reject(reason) {
    // state 状态不可变
    if (this.PromiseState!== 'pending') return
    // 如果执行 reject，状态就会变成 rejected
    this.PromiseState = 'rejected'
    // 最终结果为传入的reason
    this.PromiseResult = reason
  }
}
```
修改代码后，测试结果如下：
``` js
const test = new MyPromise((resolve, reject) => {
  resolve('成功')
  reject('失败')
})
console.log('test', test)
```
!['Promise'](/img/javascript/11.png)

#### 1.1.3 throw
!['Promise'](/img/javascript/12.png)
`Promise` 中有 `throw` 的话，就相当于执行了 `reject`。这就要使用 `try...catch` 捕获错误。
``` js
try {
  // 执行传进来的函数
  executor(this.resolve, this.reject)
} catch (error) {
  // 如果执行 reject，状态就会变成 rejected
  this.reject(error)
}
```
完整代码为：
``` js
class MyPromise {
  // 构造方法
  constructor(executor) {
    // 初始化值
    this.initValue()
    // 初始化 this 指向
    this.initBind()
    try {
      // 执行传进来的函数
      executor(this.resolve, this.reject)
    } catch (error) {
      // 如果执行 reject，状态就会变成 rejected
      this.reject(error)
    }
  }

  initValue(){
    // 初始化值
    this.PromiseResult = null // 存储最终结果
    this.PromiseState = 'pending' // 存储状态
  }

  initBind() {
    // 初始化 this 指向
    this.resolve = this.resolve.bind(this)
    this.reject = this.reject.bind(this)
  }

  resolve(value) {
    // state 状态不可变
    if (this.PromiseState !== 'pending') return
    // 如果执行 resolve，状态就会变成 fulfilled
    this.PromiseState = 'fulfilled'
    // 最终结果为传入的值
    this.PromiseResult = value
  }

  reject(reason) {
    // state 状态不可变
    if (this.PromiseState!== 'pending') return
    // 如果执行 reject，状态就会变成 rejected
    this.PromiseState = 'rejected'
    // 最终结果为传入的reason
    this.PromiseResult = reason
  }
}
```
测试代码：
``` js
const test = new MyPromise((resolve, reject) => {
  throw new Error('失败')
})
console.log('test', test)
```
!['Promise'](/img/javascript/13.png)

### 1.2 then

平时业务中 `then` 的使用一般如下：
``` js
// 场景1: 马上输出结果
const p1 = new Promise((resolve, reject) => {
  resolve('成功')
}).then((res) => {
  console.log('res', res)
}, (err) => {
  console.log('err', err)
});

// 场景2: 异步输出结果
const p2 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('成功')
  }, 1000)
}).then((res) => {
  console.log('res', res)
}, (err) => {
  console.log('err', err)
});

// 场景3: 链式调用
const p3 = new Promise((resolve, reject) => {
  resolve(10)
}).then((res) => {
  return res + 10
}, (err) => {
  console.log('err', err)
}).then((res) => {
  console.log('res', res)
}, (err) => {
  console.log('err', err)
});
```

根据上述代码可以确定：
1. `then` 接收两个回调，一个是成功回调，一个是失败回调
2. 当 `Promise` 状态为 `fulfilled` 时，会执行成功回调，当 `Promise` 状态为 `rejected` 时，会执行失败回调
3. 如果 `resolve` 或 `reject` 在定时器里，则定时器结束后再执行 `then`
4. `then` 支持链式调用，下一次 `then` 的执行受上一次 `then` 的返回值的影响

### 1.2.1 实现 then
``` js
class MyPromise {
  then(onFulfilled, onRejected) {
    // 参数校验，确保一定是函数
    if (typeof onFulfilled !== 'function') {
      onFulfilled = () => {}
    }
    if (typeof onRejected !== 'function') {
      onRejected = () => {}
    }

    // 当状态为 fulfilled 时，调用 onFulfilled
    if (this.PromiseState === 'fulfilled') {
      onFulfilled(this.PromiseResult)
    }
    // 当状态为 rejected 时，调用 onRejected
    else if (this.PromiseState === 'rejected') {
      onRejected(this.PromiseResult)
    }
  }
}
```
完整代码：
``` js
class MyPromise {
  // 构造方法
  constructor(executor) {
    // 初始化值
    this.initValue()
    // 初始化 this 指向
    this.initBind()
    try {
      // 执行传进来的函数
      executor(this.resolve, this.reject)
    } catch (error) {
      // 如果执行 reject，状态就会变成 rejected
      this.reject(error)
    }
  }

  initValue(){
    // 初始化值
    this.PromiseResult = null // 存储最终结果
    this.PromiseState = 'pending' // 存储状态
  }

  initBind() {
    // 初始化 this 指向
    this.resolve = this.resolve.bind(this)
    this.reject = this.reject.bind(this)
  }

  resolve(value) {
    // state 状态不可变
    if (this.PromiseState !== 'pending') return
    // 如果执行 resolve，状态就会变成 fulfilled
    this.PromiseState = 'fulfilled'
    // 最终结果为传入的值
    this.PromiseResult = value
  }

  reject(reason) {
    // state 状态不可变
    if (this.PromiseState!== 'pending') return
    // 如果执行 reject，状态就会变成 rejected
    this.PromiseState = 'rejected'
    // 最终结果为传入的reason
    this.PromiseResult = reason
  }

  then(onFulfilled, onRejected) {
    // 参数校验，确保一定是函数
    if (typeof onFulfilled !== 'function') {
      onFulfilled = () => {}
    }
    if (typeof onRejected !== 'function') {
      onRejected = () => {}
    }

    // 当状态为 fulfilled 时，调用 onFulfilled
    if (this.PromiseState === 'fulfilled') {
      onFulfilled(this.PromiseResult)
    }
    // 当状态为 rejected 时，调用 onRejected
    else if (this.PromiseState === 'rejected') {
      onRejected(this.PromiseResult)
    }
  }
}
```
测试代码：
``` js
const test = new MyPromise((resolve, reject) => {
  resolve('成功')
}).then((res) => {
  console.log('res', res)
}, (err) => {
  console.log('err', err)
})
```
输出结果如下：
!['Promise'](/img/javascript/14.png)

### 1.2.2 定时器

如何保证下面的代码能够在 `1s` 后执行 `then` 的回调呢？
``` js
const test = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('成功')
  }, 1000)
}).then((res) => {
  console.log('res', res)
}, (err) => {
  console.log('err', err)
});
```

我们不能保证 `1s` 后才执行 `then` 函数，但是我们可以保证 `1s` 后再执行 `then` 里的回调。
!['Promise'](/img/javascript/15.png)

在这 `1s` 的时间内，我们可以先把 `then` 里的回调保存起来，然后等到 `1s` 过后，执行了 `resolve` 或 `reject` 后，再去判断状态，并且判断要去执行刚刚保存的两个回调中的哪一个回调。

那么问题来了，我们怎么知道当前 `1s` 还没有走完甚至还没开始走呢？其实很好判断，只要状态是 `pending`，就说明 定时器还没跑完，因为如果定时器跑完的话，那状态肯定就不是 `pending` 了，而是 `fulfilled` 或 `rejected`。

那是用什么来保存这些回调呢？建议使用数组，因为一个 `Promise` 实例可能会有多个 `then` 方法，使用数组来保存多个回调。

``` js
class MyPromise {
  // 构造方法
  constructor(executor) {
    // 初始化值
    this.initValue()
    // 初始化 this 指向
    this.initBind()
    try {
      // 执行传进来的函数
      executor(this.resolve, this.reject)
    } catch (error) {
      // 捕捉到错误直接执行 reject，状态就会变成 rejected
      this.reject(error)
    }
  }

  initValue(){
    // 初始化值
    this.PromiseResult = null // 存储最终结果
    this.PromiseState = 'pending' // 存储状态
    // 存储成功回调
    this.onFulfilledCallbacks = []
    // 存储失败回调
    this.onRejectedCallbacks = []
  }

  initBind() {
    // 初始化 this 指向
    this.resolve = this.resolve.bind(this)
    this.reject = this.reject.bind(this)
  }

  resolve(value) {
    // state 状态不可变
    if (this.PromiseState!== 'pending') return
    // 如果执行 resolve，状态就会变成 fulfilled
    this.PromiseState = 'fulfilled'
    // 最终结果为传入的值
    this.PromiseResult = value
    // 执行成功回调
    while (this.onFulfilledCallbacks.length) {
      this.onFulfilledCallbacks.shift()(this.PromiseResult)
    }
  }

  reject(reason) {
    // state 状态不可变
    if (this.PromiseState!== 'pending') return
    // 如果执行 reject，状态就会变成 rejected
    this.PromiseState ='rejected'
    // 最终结果为传入的reason
    this.PromiseResult = reason
    // 执行失败回调
    while (this.onRejectedCallbacks.length) {
      this.onRejectedCallbacks.shift()(this.PromiseResult)
    }
  }

  then(onFulfilled, onRejected) {
    // 参数校验，确保一定是函数
    if (typeof onFulfilled!== 'function') {
      onFulfilled = () => {}
    }
    if (typeof onRejected!== 'function') {
      onRejected = () => {}
    }

    // 当状态为 fulfilled 时，调用 onFulfilled
    if (this.PromiseState === 'fulfilled') {
      onFulfilled(this.PromiseResult)
    } else if (this.PromiseState ==='rejected') {
      onRejected(this.PromiseResult)
    } else if (this.PromiseState === 'pending') {
      // 保存成功回调
      this.onFulfilledCallbacks.push(onFulfilled)
      // 保存失败回调
      this.onRejectedCallbacks.push(onRejected)
    }
  }
}
```

看下是否能够实现定时器的功能：
``` js
const test = new MyPromise((resolve, reject) => {
  setTimeout(() => {
    resolve('成功')
  }, 1000)
}).then((res) => {
  console.log('res', res) // 1s 后输出成功
}, (err) => {
  console.log('err', err)
});
```

### 1.2.3 链式调用

`then` 支持链式调用，下一次 `then` 的执行受上一次 `then` 的返回值的影响，举个例子：
``` js
// 链式调用 输出20
const test = new Promise((resolve, reject) => {
  resolve(10)
}).then((res) => {
  return res + 10
}, (err) => {
  console.log('err', err)
}).then((res) => {
  console.log('res', res) // 输出20
}, (err) => {
  console.log('err', err)
});

// 链式调用 输出30
const test = new Promise((resolve, reject) => {
  resolve(10)
}).then((res) => {
  return new Promise((resolve, reject) => {
    resolve(3 * res)
  })
}, (err) => {
  console.log('err', err)
}).then((res) => {
  console.log('res', res) // 输出30
}, (err) => {
  console.log('err', err)
});
```
根据上文，可以得到：
1. `then` 方法返回一个新的 `Promise` 实例
2. 如果返回值是 `Promise` 对象，返回值为成功，新的 `Promise` 就是成功
3. 如果返回值是 `Promise` 对象，返回值为失败，新的 `Promise` 就是失败
4. 如果返回值不是 `Promise` 对象，新的 `Promise` 就是成功，成功的值就是返回值

`then` 是 `Promise` 上的方法，那如何实现 `then` 执行后还能继续执行 `then` 呢？

`then` 执行后返回一个 `Promise` 对象就行了，就能保证 `then` 执行后还能继续执行 `then`。

!['Promise'](/img/javascript/16.png)

``` js
class MyPromise {
  // 构造方法
  constructor(executor) {
    // 初始化值
    this.initValue()
    // 初始化 this 指向
    this.initBind()
    try {
      // 执行传进来的函数
      executor(this.resolve, this.reject)
    } catch (error) {
      // 捕捉到错误直接执行 reject，状态就会变成 rejected
      this.reject(error)
    }
  }

  initValue(){
    // 初始化值
    this.PromiseResult = null // 存储最终结果
    this.PromiseState = 'pending' // 存储状态
    // 存储成功回调
    this.onFulfilledCallbacks = []
    // 存储失败回调
    this.onRejectedCallbacks = []
  }

  initBind() {
    // 初始化 this 指向
    this.resolve = this.resolve.bind(this)
    this.reject = this.reject.bind(this)
  }

  resolve(value) {
    // state 状态不可变
    if (this.PromiseState!== 'pending') return
    // 如果执行 resolve，状态就会变成 fulfilled
    this.PromiseState = 'fulfilled'
    // 最终结果为传入的值
    this.PromiseResult = value
    // 执行成功回调
    while (this.onFulfilledCallbacks.length) {
      this.onFulfilledCallbacks.shift()(this.PromiseResult)
    }
  }

  reject(reason) {
    // state 状态不可变
    if (this.PromiseState!== 'pending') return
    // 如果执行 reject，状态就会变成 rejected
    this.PromiseState ='rejected'
    // 最终结果为传入的reason
    this.PromiseResult = reason
    // 执行失败回调
    while (this.onRejectedCallbacks.length) {
      this.onRejectedCallbacks.shift()(this.PromiseResult)
    }
  }

  then(onFulfilled, onRejected) {
    // 参数校验，确保一定是函数
    if (typeof onFulfilled!== 'function') {
      onFulfilled = () => {}
    }
    if (typeof onRejected!== 'function') {
      onRejected = () => {}
    }

    var thenPromise = new MyPromise((resolve, reject) => {
      const resolvePromise = (cb) => {
        try {
          const x = cb(this.PromiseResult)
          if (x === thenPromise) {
            throw new Error('不能返回自身...')
          }
          if (x instanceof MyPromise) {
            // 如果返回值是 Promise 对象，返回值为成功，新的 Promise 就是成功
            // 如果返回值是 Promise 对象，返回值为失败，新的 Promise 就是失败
            x.then(resolve, reject)
          } else {
            // 如果返回值不是 Promise 对象，新的 Promise 就是成功，成功的值就是返回值
            resolve(x)
          }
        } catch (error) {
          reject(error)
          throw new Error(error)
        }
      }

      if (this.PromiseState === 'fulfilled') {
        // 如果当前为成功状态，执行第一个回调
        resolvePromise(onFulfilled)
      } else if (this.PromiseState ==='rejected') {
        // 如果当前为失败状态，执行第二个回调
        resolvePromise(onRejected)
      } else if (this.PromiseState === 'pending') {
        // 如果状态为 pending，保存回调
        this.onFulfilledCallbacks.push(() => {
          resolvePromise.bind(this, onFulfilled)
        });
        this.onRejectedCallbacks.push(() => {
          resolvePromise.bind(this, onRejected)
        });
      }
    })

    // 返回这个包装的 Promise 对象
    return thenPromise
  }
}
```

测试一下：
``` js
const test = new MyPromise((resolve, reject) => {
  resolve(10)
}).then((res) => {
  return res + 10
}, (err) => {
  console.log('err', err)
}).then((res) => {
  console.log('res', res) // 输出20
}, (err) => {
  console.log('err', err)
});

// 链式调用 输出30
const test = new MyPromise((resolve, reject) => {
  resolve(10)
}).then((res) => {
  return new MyPromise((resolve, reject) => {
    resolve(3 * res)
  })
}, (err) => {
  console.log('err', err)
}).then((res) => {
  console.log('res', res) // 输出30
}, (err) => {
  console.log('err', err)
});
```

### 1.2.4 执行顺序

这里需要了解，`then` 方法是微任务

``` js
const test = new Promise((resolve, reject) => {
  resolve(10)
}).then((res) => {
  console.log('res', res)
}, (err) => {
  console.log('err', err)
});

console.log(20);
// 输出结果为：20 10
```

这里为了实现类似的功能，使用 `setTimeout` 来模拟微任务（setTimeout实际是宏任务，此处主要是跟在全局上的console对比）

``` js
class MyPromise {
  // 构造方法
  constructor(executor) {
    // 初始化值
    this.initValue()
    // 初始化 this 指向
    this.initBind()
    try {
      // 执行传进来的函数
      executor(this.resolve, this.reject)
    } catch (error) {
      // 捕捉到错误直接执行 reject，状态就会变成 rejected
      this.reject(error)
    }
  }

  initValue(){
    // 初始化值
    this.PromiseResult = null // 存储最终结果
    this.PromiseState = 'pending' // 存储状态
    // 存储成功回调
    this.onFulfilledCallbacks = []
    // 存储失败回调
    this.onRejectedCallbacks = []
  }

  initBind() {
    // 初始化 this 指向
    this.resolve = this.resolve.bind(this)
    this.reject = this.reject.bind(this)
  }

  resolve(value) {
    // state 状态不可变
    if (this.PromiseState!== 'pending') return
    // 如果执行 resolve，状态就会变成 fulfilled
    this.PromiseState = 'fulfilled'
    // 最终结果为传入的值
    this.PromiseResult = value
    // 执行成功回调
    while (this.onFulfilledCallbacks.length) {
      this.onFulfilledCallbacks.shift()(this.PromiseResult)
    }
  }

  reject(reason) {
    // state 状态不可变
    if (this.PromiseState!== 'pending') return
    // 如果执行 reject，状态就会变成 rejected
    this.PromiseState ='rejected'
    // 最终结果为传入的reason
    this.PromiseResult = reason
    // 执行失败回调
    while (this.onRejectedCallbacks.length) {
      this.onRejectedCallbacks.shift()(this.PromiseResult)
    }
  }

  then(onFulfilled, onRejected) {
    // 参数校验，确保一定是函数
    if (typeof onFulfilled!== 'function') {
      onFulfilled = () => {}
    }
    if (typeof onRejected!== 'function') {
      onRejected = () => {}
    }

    var thenPromise = new MyPromise((resolve, reject) => {
      const resolvePromise = (cb) => {
        setTimeout(() => {
          try {
            const x = cb(this.PromiseResult)
            if (x === thenPromise) {
              throw new Error('不能返回自身...')
            }
            if (x instanceof MyPromise) {
              // 如果返回值是 Promise 对象，返回值为成功，新的 Promise 就是成功
              // 如果返回值是 Promise 对象，返回值为失败，新的 Promise 就是失败
              x.then(resolve, reject)
            } else {
              // 如果返回值不是 Promise 对象，新的 Promise 就是成功，成功的值就是返回值
              resolve(x)
            }
          } catch (error) {
            reject(error)
            throw new Error(error)
          }
        })
      }

      if (this.PromiseState === 'fulfilled') {
        // 如果当前为成功状态，执行第一个回调
        resolvePromise(onFulfilled)
      } else if (this.PromiseState ==='rejected') {
        // 如果当前为失败状态，执行第二个回调
        resolvePromise(onRejected)
      } else if (this.PromiseState === 'pending') {
        // 如果状态为 pending，保存回调
        this.onFulfilledCallbacks.push(() => {
          resolvePromise.bind(this, onFulfilled)
        });
        this.onRejectedCallbacks.push(() => {
          resolvePromise.bind(this, onRejected)
        });
      }
    })

    // 返回这个包装的 Promise 对象
    return thenPromise
  }
}
```

测试一下：
``` js
const test = new MyPromise((resolve, reject) => {
  resolve(10)
}).then((res) => {
  console.log('res', res)
}, (err) => {
  console.log('err', err)
});

console.log(20);
```

### 1.3 其它方法

#### 1.3.1 all

1. 接收一个 `Promise` 数组，数组中如果有非 `Promise` 项，则此项当作成功
2. 如果所有 `Promise` 都成功，则返回成功结果数组
3. 如果有一个 `Promise` 失败，则返回这个失败结果

``` js
class MyPromise {
  static all(promises) {
    const result = []
    let count = 0

    return new MyPromise((resolve, reject) => {
      const addData = (index, value) => {
        result[index] = value
        count++
        if (count === promises.length) {
          resolve(result)
        }
      }

      promises.forEach((item, index) => {
        if (item instanceof MyPromise) {
          item.then((res) => {
            addData(index, res)
          })
        } else {
          addData(index, item)
        }
      })
    })
  }
}
```

#### 1.3.2 race

1. 接收一个 `Promise` 数组，数组中如果有非 `Promise` 项，则此项当作成功
2. 哪个 `Promise` 先成功或失败，就返回哪个 `Promise` 的结果

``` js
class MyPromise {
  static race(promises) {
    return new MyPromise((resolve, reject) => {
      promises.forEach((item) => {
        if (item instanceof MyPromise) {
          item.then(res => {
            resolve(res)
          }, err => {
            reject(err)
          })
        } else {
          resolve(item)
        }
      })
    })
  }
}
```

#### 1.3.3 allSettled

1. 接收一个 `Promise` 数组，数组中如果有非 `Promise` 项，则此项当作成功
2. 所有 `Promise` 都成功或失败后，返回结果数组

``` js
class MyPromise {
  static allSettled(promises) {
    return new MyPromise((resolve, reject) => {
      const result = []
      let count = 0

      const addData = (index, status, value) => {
        result[index] = {
          status,
          value
        }
        count++
        if (count === promises.length) {
          resolve(result)
        }
      }

      promises.forEach((item, index) => {
        if (item instanceof MyPromise) {
          item.then((res) => {
            addData(index, 'fulfilled', res)
          }, (err) => {
            addData(index, 'rejected', err)
          }
        } else {
          addData(index, 'fulfilled', item)
        }
      })
    })
  }
}
```

#### 1.3.4 any

1. 接收一个 `Promise` 数组，数组中如果有非 `Promise` 项，则此项当作成功
2. 如果有一个 `Promise` 成功，则返回这个成功结果
3. 如果所有 `Promise` 都失败，则报错

``` js
class MyPromise {
  static any(promises) {
    return new MyPromise((resolve, reject) => {
      let count = 0

      promises.forEach((item) => {
        item.then((res) => {
          resolve(res)
        }, (err) => {
          count++
          if (count === promises.length) {
            reject('All promises were rejected')
          }
        }
      })
    })
  }
}
```

### 1.4 异步案例

实现一个带并发限制的异步调度器 `Scheduler`，保证同时运行的任务最多有N个。完善下面的 `Scheduler` 类，使以下程序能正确输出：

``` js
class Scheduler {
  add(promiseCreator) {
    // ...
  }
  // ...
}

const timeout = (time) => new Promise(resolve => {
  setTimeout(resolve, time)
})

const scheduler = new Scheduler(n)
const addTask = (time, order) => {
  scheduler.add(() => timeout(time))
    .then(() => console.log(order))
}

addTask(1000, '1')
addTask(500, '2')
addTask(300, '3')
addTask(400, '4')
// 输出：2 3 1 4

```

流程分析，完整的执行流程如下：
1. 起始1、2两个任务开始执行
2. 500ms时，任务2执行完毕，输出2，任务3开始执行
3. 800ms时，任务3执行完毕，输出3，任务4开始执行
4. 1000ms时，任务1执行完毕，输出1，此时只剩下任务4在执行
5. 1200ms时，任务4执行完毕，输出4

当资源不足时将任务添加到等待队列中，当资源可用时，从等待队列中取出任务执行。

在调度器中一般会有一个等待队列 `queue`，用于存储当资源不够时的待执行的任务。

具有并发数据限制，假设通过 `max` 设置允许同时运行的任务，还需要一个 `count` 变量，用于记录当前正在运行的任务数量。

当需要执行一个任务A时，先判断 `count` 是否小于 `max`，如果小于，则直接执行任务A，并且 `count++`。如果大于等于 `max`，则将任务A添加到等待队列 `queue` 中。

当任务A执行完毕时，`count--`，并且从等待队列 `queue` 中取出一个任务B执行，直到等待队列 `queue` 为空。

``` js
class Scheduler {
  constructor(max) {
    this.max = max
    this.count = 0  // 当前正在运行的任务数量
    this.queue = [] // 等待队列
  }
  async add(promiseCreator) {
    if (this.count >= this.max) {
      // 当资源不足时，将任务添加到等待队列中
      await new Promise(resolve => {
        this.queue.push(resolve)
      })
    }
    this.count++
    const res = await promiseCreator()
    this.count--
    if(this.queue.length > 0) {
      // 从等待队列中取出一个任务执行
      this.queue.shift()()
    }
    return res
  }
}

const timeout = (time) => new Promise(resolve => {
  setTimeout(resolve, time)
});
const scheduler = new Scheduler(2);

const addTask = (time, order) => {
  scheduler.add(() => timeout(time))
    .then(() => console.log(order));
};

addTask(1000, '1');
addTask(500, '2');
addTask(300, '3');
addTask(400, '4');
// 输出：2 3 1 4
```

## 2. Promise A+ 规范

官网地址：
- https://promisesaplus.com.cn/
- https://promisesaplus.com/

Promise 表示一个异步操作的最终结果，与之进行交互的方式主要是 `.then` 方法，该方法注册了两个回调函数，用于接收 Promise 的终值或本 Promise 不能执行的原因。

本规范详细列出了 `.then` 方法的执行过程，所有遵循 Promises/A+ 规范实现的 Promise 均可以本标准作为参照基础来实施 `.then` 方法。因而本规范是十分稳定的。尽管 Promise/A+ 组织有时可能会修订本规范，但主要是为了处理一些特殊的边界情况，且这些改动都是微小且向下兼容的。如果我们要进行大规模不兼容的更新，我们一定会在事先进行谨慎地考虑、详尽的探讨和严格的测试。

从历史上说，本规范实际上是把之前 Promise/A 规范 中的建议明确成为了行为标准：我们一方面扩展了原有规范约定俗成的行为，一方面删减了原规范的一些特例情况和有问题的部分。

最后，核心的 Promises/A+ 规范不设计如何创建、解决和拒绝 Promise，而是专注于提供一个通用的 `.then` 方法。上述对于 Promises 的操作方法将来在其他规范中可能会提及。

### 2.1 规范术语

- 解决（fulfill）：指一个 Promise 成功时进行的一系列操作，如状态的改变、回调的执行。虽然规范中用 fulfill 来表示解决，但在后世的 Promise 实现多以 resolve 来指代之。
- 拒绝（reject）：指一个 Promise 失败时进行的一系列操作。
- 终值（eventual value）：所谓终值，指的是 Promise 被解决时传递给解决回调的值，由于 Promise 有一次性的特征，因此当这个值被传递时，标志着 Promise 等待态的结束，故称之终值，有时也直接简称为值（value）。
- 拒因（reason）：也就是拒绝原因，指在 Promise 被拒绝时传递给拒绝回调的值。

### 2.2 术语

- Promise：Promise 是一个拥有 .then 方法的对象或函数，其行为符合本规范；
- thenable：是一个定义了 .then 方法的对象或函数，文中译作"拥有 .then 方法"；
- 值（value）：指任何 JavaScript 的合法值（包括 undefined、thenable 和 Promise）；
- 异常（exception）：是使用 throw 语句抛出的一个值。
- 拒因（reason）：表示一个 Promise 的拒绝原因。

## 3. async/await

### 3.1 介绍

async/await 是 ES2017 引入的一个新的语法特性，它是 Promise 的语法糖，用于更方便地处理异步操作。

``` js
function request(num) { // 模拟接口请求
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(num * 2)
    }, 1000)
  })
}

request(1).then((res1) => {
  console.log(res1) // 1秒后输出2
  return request(2).then((res2) => {
    console.log(res2) // 2秒后输出4
  })
})
```

现在有一个新的要求：先请求完接口1，再拿接口1返回的数据，去当作接口2的请求参数，那我们也可以这么做：
``` js
request(1).then((res1) => {
  console.log(res1) // 1秒后输出2
  request(res1).then((res2) => {
    console.log(res2) // 3秒后输出4
  })
})
```

如果嵌套的层级多了，代码会变得非常复杂，可读性也会很差。这时候就可以用 `async/await` 来解决这个问题。

``` js
async function fn() {
  const res1 = await request(1)
  const res2 = await request(res1)
  console.log(res2) // 3秒后输出4
}
fn()
```

在 `async` 函数中，`await` 规定了异步操作只能一个一个排队执行，从而达到同步方式，执行异步操作的结果。
> 注意：`await` 只能在 `async` 函数中使用。

刚刚上面的例子 `await` 后面都是跟着异步操作 `Promise`，那如果不接 `Promise` 呢？

``` js
function request(num) {
  setTimeout(() => {
    console.log(num * 2)
  }, 1000)
}

async function fn() {
  await request(1)  // 1秒后输出2
  await request(2)  // 1秒后输出4
  // 1秒后执行完，同时输出
}
fn()
```

可以看出，如果 `await` 后面接的不是 `Promise` 的话，其实是达不到类似同步的效果的。

Q：什么是 `async` ？`async` 是一个位于 `function` 之前的前缀，只有 `async` 函数才能使用 `await`。那么 `async` 执行的结果返回是什么呢？
``` js
async function fn() {}  
console.log(fn) // async function fn() {}
console.log(fn(10)) // Promise {<fulfiled>: 10}
fn(10).then((res) => {
  console.log(res) // 10
})
```

#### 3.1.1 总结

1. `await` 只能在 `async` 函数中使用，不然会报错
2. `async` 函数返回的是一个 `Promise` 对象，有无值看有无 `return` 的值
3. `await` 后面最好是接 `Promise`，虽然接其它值也能达到排队执行的效果
4. `async/await` 作用是用同步方式，执行异步操作

#### 3.1.2 语法糖

Q：`async/await` 是一种语法糖，那么什么是语法糖呢？
A：语法糖是简化代码的一种方式，用其它方式也能达到同样的效果，但是写法可能没有那么便利。

ES6 中的 `class` 就是一种语法糖，它的作用是简化 `class` 的写法。

回归正题，`async/await` 是一种语法糖，用到的是 ES6 中的迭代函数 ———— generator函数。